"""Build static numeric signal/function IDs and their separately readable codebook."""
import ast
import hashlib
import json
from pathlib import Path
import re
import runpy

ROOT = Path(__file__).resolve().parents[2]
events = runpy.run_path(str(ROOT/'cfd_bot/diagnostic_codec.py'))['EVENTS'].copy()
functions, discovered = [], set()
for path in sorted((ROOT/'cfd_bot').glob('*.py')):
    tree = ast.parse(path.read_text())
    def visit(node, parents=()):
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            parents = (*parents, node.name)
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and any(isinstance(d, ast.Attribute) and d.attr=='trace' for d in node.decorator_list):
                functions.append(path.stem+'.'+'.'.join(parents))
        for child in ast.iter_child_nodes(node): visit(child, parents)
    visit(tree)
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and node.args and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str):
            fn = node.func.id if isinstance(node.func, ast.Name) else node.func.attr if isinstance(node.func, ast.Attribute) else ''
            if fn in ('event', '_write') and re.fullmatch(r'[a-z]+[a-z_.]+', node.args[0].value): discovered.add(node.args[0].value)
for path in (ROOT/'bin/ofps', ROOT/'bin/ofps-diagnostics.sh'):
    discovered.update(re.findall(r'_cfd_diag_write ([a-z]+[a-z_.]+)', path.read_text()))
for number, name in enumerate(sorted(discovered-set(events.values())), 1000): events[number] = name
js = sorted(set(re.findall(r'"(web\.ui\.[^"\n]+)"', (ROOT/'cfd_bot/web_static/app.js').read_text())))
shell = sorted(set(re.findall(r'^([a-z_]+)\(\)', (ROOT/'bin/ofps').read_text(), re.M))|{'main'})
book = {'schema_version':2, 'event_codes':events, 'function_codes':sorted(set(functions)),
        'javascript_functions':js, 'shell_functions':shell}
raw = (json.dumps(book,ensure_ascii=False,indent=2)+'\n').encode()
digest = hashlib.sha256(raw).hexdigest()
(ROOT/'cfd_bot/diagnostic_codes.json').write_bytes(raw)
(ROOT/'cfd_bot/web_static/diagnostic_codes.js').write_text("'use strict';\nconst CFD_DIAGNOSTIC_CODES = "+json.dumps(dict(book,sha256=digest),ensure_ascii=False,separators=(',',':'))+';\n')
shell_constants = ['# Generated by docs/analysis/build_diagnostic_codes.py; no runtime decisions.',
                   'declare -A _cfd_diag_event_codes=('+' '.join(f'[{name}]={number}' for number,name in events.items())+')',
                   'declare -A _cfd_diag_function_codes=('+' '.join(f'[{name}]={number}' for number,name in enumerate(shell))+')',
                   "_cfd_diag_event_json='"+json.dumps(events,separators=(',',':'))+"'",
                   "_cfd_diag_function_json='"+json.dumps(shell,separators=(',',':'))+"'",
                   "_cfd_diag_codebook_sha='"+digest+"'"]
(ROOT/'bin/ofps-diagnostic-codes.sh').write_text('\n'.join(shell_constants)+'\n')
lines = ['# 진단 코드 사전 — schema 2', '', f'사전 SHA-256: `{digest}`.', '',
         '[기계 사전](../../cfd_bot/diagnostic_codes.json) · [형식/복원](../DIAGNOSTICS.md) · [#30](https://github.com/jo0n-lab/cfd-bot/issues/30).', '',
         '번호는 이 사전 버전에서만 해석한다. HTTP status 및 POSIX signal 번호와 별개다. 모든 파일은 해당 사전/필요 정의를 포함하여 회전 후에도 읽는다. 비밀값이 제거된 입력/반환과 실제 분기만 기록하며 업무 판단은 추가하지 않는다.', '',
         'Python 공통 row: `[event_code, delta_ns, delta_seq, context_id, call_ref, parent_ref, ...]`. call tail은 `[function_id, caller_value_ref, input_ref, parent_trace]`, return은 `[function_id, duration_ns, result_ref, steps]`, raise는 `[function_id, duration_ns, error_refs, steps]`다. 다른 event는 `[fields_ref, steps, error_refs]`를 사용한다. values/context/calls/error 사전은 batch마다 독립적이다. base UTC ns는 문자열로 보관한다.', '',
         'Browser row: `[event_code, delta_mono_ms, seq, call, parent, ...]`. call tail은 `[function_id, input_ref, interaction_id]`, return/raise는 `[function_id, duration_ms, result_ref]`, 나머지는 `[fields_ref]`다. shell row의 함수 번호는 아래 shell 표를 사용한다. 원래 exit code 및 PIPESTATUS는 별도 값으로 보존한다.', '',
         '| Event code | 의미 |', '|---:|---|']
lines += [f'| {number} | `{name}` |' for number,name in sorted(events.items())]
for title,key in [('Python 함수','function_codes'),('Browser 함수','javascript_functions'),('ofps 함수','shell_functions')]:
    lines += ['', '## '+title, '', '| ID | 함수 |', '|---:|---|']
    lines += [f'| {index} | `{name}` |' for index,name in enumerate(book[key])]
lines += ['', '분기 ID·소스 위치·HLD/LLD 103개 시퀀스는 [flow 대응표](diagnostic-flow-coverage.md)와 별도 source map에 있다. 동적 테스트/외부 callback은 알려지지 않은 함수 이름을 그대로 기록하며 사전에 없는 숫자 ID를 추정하지 않는다.', '']
(ROOT/'docs/analysis/diagnostic-codebook.md').write_text('\n'.join(lines))
print(json.dumps({'sha256':digest,'events':len(events),'functions':len(functions),'javascript':len(js),'shell':len(shell)}))
