'use strict';
const $ = (q, root=document) => root.querySelector(q);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attr = esc;
const S = {csrf:'', overview:null, draft:null, tab:'basic', selected:new Set(), search:'', patterns:{}, cases:[], dataId:null, refreshing:false, busy:false, postprocessed:[], browser:null};
const names = {overview:'대시보드',tickets:'티켓 관리',queue:'작업 큐',data:'결과 · 요청 데이터'};
const statusNames = {idle:'실행 가능',running:'계산 중',queued:'대기 중',waiting:'계산 대기',starting:'시작 중',postprocessing:'후처리 중',finished:'계산 종료',succeeded:'완료',failed:'실패',interrupted:'중단',cancelled:'취소',invalid:'확인 필요'};
let modalAction = null, toastTimer;
const view = () => names[location.hash.slice(1)] ? location.hash.slice(1) : 'overview';
const badge = (status, label) => `<span class="status ${attr(status)}">${esc(label || statusNames[status] || status)}</span>`;
const empty = (text, mark='◌') => `<div class="empty"><span class="empty-mark">${mark}</span>${esc(text)}</div>`;
const duration = n => n == null || !Number.isFinite(n) ? '—' : n < 60 ? `${Math.max(0,Math.floor(n))}초` : n < 3600 ? `${Math.floor(n/60)}분` : `${Math.floor(n/3600)}시간 ${Math.floor(n%3600/60)}분`;
const stamp = n => n ? new Date(n*1000).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}) : '—';
const bytes = n => n < 1024*1024 ? `${(n/1024).toFixed(1)} KB` : `${(n/1024/1024).toFixed(1)} MB`;
const btn = (action, text, cls='', more='') => `<button data-action="${action}" class="${cls}" ${more}>${text}</button>`;
function toast(message, error=false) { const el=$('#toast'); el.textContent=message; el.className=error?'error':''; el.hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.hidden=true,error?9000:4000); }
async function api(path, data) {
  const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':S.csrf}:{},body:data?JSON.stringify(data):undefined});
  const result=await response.json(); if(!response.ok) throw new Error(result.error || '요청 실패'); return result;
}
function modal(title, body, label, action, danger=false) {
  $('#modal-title').textContent=title; $('#modal-body').innerHTML=body;
  $('#modal-actions').innerHTML=btn('close-modal','닫기')+(label?btn('confirm-modal',esc(label),danger?'danger':'primary'):'');
  modalAction=action; if(!$('#modal').open) $('#modal').showModal();
}
function confirmDiscard(action) {
  if(!S.draft?.dirty) return action();
  modal('저장하지 않은 변경 내용', '<p>현재 초안의 변경 내용을 버리고 계속할까요?</p>', '버리고 계속', async()=>{ S.draft=null; await action(); });
}
function heading(k,title,sub,actions=''){return `<div class="page-head"><div><div class="eyebrow">${k}</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="actions">${actions}</div></div>`;}
function queueRows(jobs, compact=false){
  if(!jobs.length)return empty('대기 중인 작업이 없습니다.');
  if(compact)return jobs.slice(0,6).map((j,i)=>`<div class="queue-item"><span class="queue-number">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(j.name)}</strong><small>${esc(j.actual_cores ? j.actual_cores+' cores · ' : '')}${esc(j.id)}</small></div>${badge(j.status)}</div>`).join('');
  return `<div class="table-wrap"><table><thead><tr><th>순서 / 작업</th><th>상태</th><th>CPU 배치</th><th>등록 / 시작</th><th></th></tr></thead><tbody>${jobs.map((j,i)=>`<tr><td><strong>${i+1}. ${esc(j.name)}</strong><small title="${attr(j.case_dir)}">${esc(j.case_dir)}</small></td><td>${badge(j.status)}</td><td class="mono">${esc(j.actual_cpu_list || '가용 코어 자동 배정')}<small>${j.actual_cores?esc(j.actual_cores)+' cores':''}</small></td><td>${stamp(j.started||j.created)}</td><td>${j.status==='queued'?btn('cancel-job','대기 취소','small',`data-id="${attr(j.id)}"`):''}</td></tr>`).join('')}</tbody></table></div>`;
}
function historyTable(jobs){return !jobs.length?empty('아직 실행 이력이 없습니다.'):`<div class="table-wrap"><table><thead><tr><th>케이스</th><th>결과</th><th>종료 시각</th><th>실행 시간</th><th>상세</th></tr></thead><tbody>${jobs.map(j=>`<tr><td><strong>${esc(j.name)}</strong><small>${esc(j.id)}</small></td><td>${badge(j.status)}</td><td>${stamp(j.finished)}</td><td>${duration(j.started&&j.finished?j.finished-j.started:null)}</td><td>${btn('job-detail','상세 보기','link-button',`data-id="${attr(j.id)}"`)}</td></tr>`).join('')}</tbody></table></div>`;}
function overview(){
  const o=S.overview;if(!o)return empty('상태를 불러오는 중…');
  const cpus=new Set(o.live.flatMap(r=>String(r.actual_cpu_list||'').split(',').flatMap(chunk=>{const [a,b]=chunk.split('-').map(Number); return Number.isFinite(a)?Array.from({length:Math.min(4096,(b??a)-a+1)},(_,i)=>a+i):[];})).filter(n=>Number.isFinite(n)));
  return heading('SIMULATION OVERVIEW','계산을 한눈에.','실행 중인 케이스와 다음 작업, 최신 결과를 확인하세요.',btn('new-single','＋ 개별 티켓')+btn('new-macro','＋ 매크로 만들기','primary'))+
    `<div class="stats"><div class="stat"><div class="stat-label">실행 중 ${badge('running','LIVE')}</div><strong>${o.live.length}<small>케이스</small></strong><div class="stat-foot">외부에서 시작한 계산 포함</div></div><div class="stat"><div class="stat-label">작업 큐 <span>≋</span></div><strong>${o.queue.filter(j=>j.status==='queued').length}<small>대기</small></strong><div class="stat-foot">${o.paused?'자동 시작 일시 정지':o.scheduler_enabled?'가용 CPU 확보 후 순차 실행':'컨트롤러 자동 실행 꺼짐'}</div></div><div class="stat"><div class="stat-label">사용 중 CPU <span>▦</span></div><strong>${o.live.length?cpus.size:0}<small>cores</small></strong><div class="stat-foot">ofps에서 확인된 실제 CPU 배치</div></div><div class="stat"><div class="stat-label">저장된 티켓 <span>▤</span></div><strong>${o.tickets.length}<small>개</small></strong><div class="stat-foot">매크로 ${o.tickets.filter(t=>t.task_type==='macro').length}개 · 개별 ${o.tickets.filter(t=>t.task_type!=='macro').length}개</div></div></div>`+
    `<div class="grid-two"><section class="panel"><div class="panel-head"><div><h2>실행 중인 케이스</h2><small>ofps의 최신 실행 상태</small></div>${badge('running',o.live.length+' ACTIVE')}</div>${o.live.length?o.live.map(r=>{const e=r.estimate||{};return `<div class="run-card"><div class="run-top"><h3>${r.registered?`<button class="link-button" data-action="case-data" data-id="${attr(r.case_id)}">${esc(r.name)}</button>`:esc(r.name)}</h3>${badge('running')}</div><p class="run-path mono">${esc(r.case_dir)}</p><div class="run-metrics"><div><label>현재 / 목표</label><strong>${esc(r.time??'—')} <small>/ ${esc(e.target??'—')}</small></strong></div><div><label>경과 시간</label><strong>${duration(Date.now()/1000-r.started)}</strong></div><div><label>예상 남은 시간</label><strong>${duration(e.remaining_seconds)}</strong></div><div><label>할당 CPU</label><strong>${esc(r.actual_cores??'—')} <small>cores</small></strong></div></div><progress max="1" value="${attr(e.progress??0)}" aria-label="계산 진행률"></progress><p class="foot-note">CPU ${esc(r.actual_cpu_list||'—')} · ${esc(r.owner||'')} ${r.registered?'':'· 외부 실행'}</p></div>`;}).join(''):empty('현재 실행 중인 계산이 없습니다.','◉')}</section><section class="panel"><div class="panel-head"><div><h2>다음 작업</h2><small>동일 코어의 중복 배정 없이 실행</small></div><a href="#queue">전체 보기 ↗</a></div>${queueRows(o.queue,true)}</section></div><section class="panel"><div class="panel-head"><h2>최근 실행 이력</h2><a href="#queue">모든 이력 ↗</a></div>${historyTable(o.history.slice(0,6))}</section>`;
}
function queuePage(){const o=S.overview;if(!o)return empty('상태를 불러오는 중…');return heading('EXECUTION QUEUE','작업 큐','등록된 순서와 CPU 가용 상태에 따라 기존 봇이 계산을 실행합니다.',btn(o.paused?'resume-queue':'pause-queue',o.paused?'▶ 자동 시작 재개':'Ⅱ 자동 시작 일시 정지',o.paused?'primary':''))+(!o.scheduler_enabled?'<div class="notice warning">bot 설정에서 자동 실행이 꺼져 있습니다. 큐에 등록된 작업은 scheduler.enabled가 켜질 때 실행됩니다.</div>':'')+(o.paused?'<div class="notice warning">새 계산의 자동 시작을 일시 정지했습니다. 현재 실행 중인 계산은 계속 진행됩니다.</div>':'')+`<section class="panel"><div class="panel-head"><h2>대기 · 실행 중</h2><small>${o.queue.length}개 작업</small></div>${queueRows(o.queue)}</section><section class="panel"><div class="panel-head"><h2>실행 이력</h2><small>최근 100개</small></div>${historyTable(o.history)}</section>`;}
function ticketList(){const rows=(S.overview?.tickets||[]).filter(t=>(t.name+' '+t.filename).toLowerCase().includes(S.search.toLowerCase()));return rows.length?rows.map(t=>`<div class="ticket-row ${S.draft?.current===t.filename?'selected':''}"><input type="checkbox" data-select="${attr(t.filename)}" ${S.selected.has(t.filename)?'checked':''} aria-label="${attr(t.name)} 선택"><button data-action="open-ticket" data-name="${attr(t.filename)}"><strong>${esc(t.name)}</strong><small>${esc(t.filename)}</small><span class="type">${t.task_type==='macro'?'MACRO · '+t.count:t.role==='child'?'CHILD':'SINGLE'}</span>${badge(t.state)}</button></div>`).join(''):empty('표시할 티켓이 없습니다.');}
function inputField(key,label,placeholder='',hint='',browse=false,type='text'){const v=S.draft.values;return `<div class="field"><label for="f-${key}">${label}</label><div class="input-action"><input id="f-${key}" data-field="${key}" type="${type}" value="${attr(v[key])}" placeholder="${attr(placeholder)}">${browse?btn('browse',key==='case_dir'?'폴더 선택':'파일 선택','',`data-field-target="${key}"`):''}</div>${hint?`<small>${hint}</small>`:''}</div>`;}
function textareaField(key,label,hint='',browse=false){return `<div class="field"><label for="f-${key}">${label}</label>${browse?`<div class="actions">${btn('browse','파일 선택으로 추가','small',`data-field-target="${key}"`)}</div>`:''}<textarea id="f-${key}" data-field="${key}" spellcheck="false">${esc(S.draft.values[key])}</textarea>${hint?`<small>${hint}</small>`:''}</div>`;}
function executionForm(v){
  const macro=v.task_type==='macro',child=!macro&&v.role==='child',explicit=macro||v.execution_source==='ticket';
  const source=macro?'':child?`<div class="notice">매크로 실행 설정을 상속합니다. 변경은 부모 티켓 <strong>${esc(v.macro_ticket)}</strong>에서 하세요.</div>`:`<div class="field"><label for="execution-source">실행 설정 방식</label><select id="execution-source" data-field="execution_source"><option value="case" ${!explicit?'selected':''}>케이스 설정 사용</option><option value="ticket" ${explicit?'selected':''}>티켓에서 지정</option></select><small>케이스 설정 사용 시 기존 Allrun / config/*Run의 NP와 실행 설정을 유지합니다.</small></div>`;
  if(!explicit&&!child)return source;
  return source+`<div class="notice">병렬 CPU 개수만 지정하면 가용한 코어를 자동 배정합니다. 소켓을 넘어 사용할 수 있으며 실행 중인 작업과 코어가 겹치지 않습니다.</div><fieldset ${child?'disabled':''} class="execution-fields">${inputField('macro_cores','병렬 CPU 개수','예: 48',macro?'모든 하위 케이스에 공통 적용합니다.':'이 티켓의 실행에 적용합니다.',false,'number')}${inputField('macro_command','실행 명령','./Allrun','보통 ./Allrun을 사용합니다.')}<details><summary>고급 CPU 설정</summary><p class="foot-note">자동 배정을 권장합니다. 수동 설정은 기존 티켓 호환을 위해 제공합니다.</p><div class="field"><label for="cpu-policy">CPU 배정 방식</label><select id="cpu-policy" data-field="macro_cpu_policy"><option value="auto" ${v.macro_cpu_policy==='auto'?'selected':''}>자동 배정 (권장)</option><option value="manual" ${v.macro_cpu_policy==='manual'?'selected':''}>수동 배정</option></select></div>${v.macro_cpu_policy==='manual'?inputField('macro_cpu_set','CPU 범위','0-23,26-49')+`<label class="check-label"><input type="checkbox" data-field="macro_cross_socket" ${v.macro_cross_socket?'checked':''}>소켓 간 실행 허용</label>`:''}</details></fieldset>`;
}
function editor(){if(!S.draft)return `<section class="panel">${empty('왼쪽에서 티켓을 선택하거나 새 티켓을 만드세요.','▤')}</section>`;
  const d=S.draft,v=d.values,macro=v.task_type==='macro';
  const state=(S.overview?.tickets||[]).find(t=>t.filename===d.current)||d.run_state||{state:'idle',enabled:true};
  const tabs=[['basic','기본 설정'],['rules','종료 · 실패 판정'],['exports','요청 데이터'],['scripts','전·후처리'],['resources','실행 설정'],...(macro?[['macro','하위 케이스']]:[])];
  if(!tabs.some(t=>t[0]===S.tab))S.tab='basic';
  let form='';
  if(S.tab==='basic')form=`<div class="form-grid"><div class="field"><label for="task-type">작업 종류</label><select id="task-type" data-field="task_type"><option value="single" ${!macro?'selected':''}>개별 작업</option><option value="macro" ${macro?'selected':''}>매크로 작업</option></select></div>${inputField('name','표시 이름','케이스 이름')}<div class="full">${inputField('case_dir','Case directory <span aria-label="필수">*</span>','/home/…/OpenFOAM/…/run/…','절대 경로를 입력하거나 폴더를 선택하세요.',true)}</div>${inputField('end_time','End Time / Iteration','controlDict 기본값','비워 두면 controlDict의 endTime을 사용합니다.','', 'number')}<div class="field"><label for="ticket-filename">티켓 파일명</label><input id="ticket-filename" data-filename value="${attr(d.filename)}" placeholder="이름으로 자동 생성"><small>macro- / child- / alone- 접두사는 자동 적용됩니다.</small></div>${!macro?`<div class="field"><label for="ticket-role">소속</label><select id="ticket-role" data-field="role"><option value="alone" ${v.role==='alone'?'selected':''}>Alone · 독립 케이스</option><option value="child" ${v.role==='child'?'selected':''}>Child · 매크로 하위 케이스</option></select><small>Child는 매크로의 하위 케이스 목록에서 생성합니다.</small></div>${v.role==='child'?inputField('macro_ticket','부모 매크로 티켓','macro-example.json'):''}`:''}<div class="full" id="control-hint"></div></div>${textareaField('logs','로그 파일','케이스 기준 상대 경로. 여러 파일은 한 줄에 하나씩 입력합니다.',true)}${inputField('residual_pattern','Residual PNG 경로','validation/monitoring/preFlow/residuals.png','케이스에서 생성한 PNG를 사용합니다. residual*.png 같은 패턴도 가능합니다.',true)}<div class="field"><span class="field-label">Telegram 알림</span><div class="check-group">${[['started','시작'],['succeeded','정상 종료'],['failed','실패'],['interrupted','중단']].map(([key,text])=>`<label class="check-label"><input type="checkbox" data-event="${key}" ${v.events.includes(key)?'checked':''}>${text}</label>`).join('')}</div></div>`;
  if(S.tab==='rules')form=`<div class="notice">정상 종료는 controlDict의 종료 조건과 최신 로그의 최종 Time으로 판단합니다.</div><label class="field-label" for="preset">실패 패턴 템플릿</label><div class="preset-row"><select id="preset">${Object.keys(S.patterns).map(name=>`<option>${esc(name)}</option>`).join('')}</select>${btn('apply-preset','적용')}${btn('save-preset','템플릿 저장')}</div>${textareaField('failure_patterns','실패 로그 패턴','정규식 하나를 한 줄씩 입력하세요. 비워 두어도 기본 OpenFOAM 오류 감지는 사용할 수 있습니다.')}<div class="field"><label class="check-label"><input type="checkbox" data-field="openfoam_defaults" ${v.openfoam_defaults?'checked':''}>기본 OpenFOAM 오류 패턴 포함</label></div>${textareaField('updated_files','갱신 여부를 확인할 파일','케이스 기준 상대 경로를 한 줄에 하나씩 입력하세요.')}`;
  if(S.tab==='exports')form=`<div class="notice">요청 시 확인하거나 다운로드할 데이터를 정의합니다. 매크로에서는 모든 하위 케이스에 같은 상대 경로를 적용합니다.</div><div id="export-rows">${exportRows()}</div>${btn('add-export','＋ 요청 데이터 추가')}`;
  if(S.tab==='scripts')form=`<div class="notice warning">전처리는 계산 시작 전에, 후처리는 계산 종료 후에 실행됩니다. Allclean은 케이스 결과를 정리할 수 있으므로 실행 전 설정을 확인하세요.</div>${textareaField('preprocess','전처리 스크립트','기본값: ./Allclean · 한 줄에 명령 하나. 비우면 실행하지 않습니다.')}${textareaField('postprocess','후처리 스크립트','기본값: ./Allpost · 한 줄에 명령 하나. 비우면 실행하지 않습니다.')}`;
  if(S.tab==='resources')form=executionForm(v);
  if(S.tab==='macro')form=`<div class="notice">Allrun이 있는 하위 케이스를 검색합니다. 실행 중인 케이스와 *-template 폴더는 제외합니다. postProcessing이 있는 케이스는 노란색으로 표시합니다.</div><div class="actions">${btn('discover','⌕ 하위 케이스 검색','primary')}<small>현재 목록을 검색 결과로 교체합니다.</small></div><p class="row-count">선택된 케이스 ${v.cases.length}개 · 위에서 아래 순서로 실행</p>${v.cases.length?v.cases.map((r,i)=>`<div class="macro-row ${S.postprocessed.includes(r.case_dir)?'has-post':''}"><span class="queue-number">${i+1}</span><div><strong>${esc(r.case_dir.split('/').pop())}</strong><p class="mono">${esc(r.case_dir)}</p><p>${esc(r.reason||statusNames[r.state]||'계산 대기')}</p></div><div class="actions">${btn('case-up','↑','small',`data-index="${i}" ${i===0?'disabled':''} aria-label="위로"`)}${btn('case-down','↓','small',`data-index="${i}" ${i===v.cases.length-1?'disabled':''} aria-label="아래로"`)}${btn('remove-case','삭제','small danger',`data-index="${i}"`)}</div></div>`).join(''):empty('아직 선택된 케이스가 없습니다.')}`;
  return `<section class="panel editor"><div class="editor-head"><div><div class="eyebrow">${macro?'MACRO TICKET':v.role==='child'?'CHILD TICKET':'SINGLE TICKET'}</div><h2>${esc(v.name||'새 티켓')}</h2><p>${esc(d.current||'저장 전 새 티켓')}</p></div><div class="actions">${badge(state.state)}${d.current?btn('duplicate-ticket','복제','small'):''}</div></div><div class="editor-tabs" role="tablist">${tabs.map(([key,label])=>`<button role="tab" aria-selected="${S.tab===key}" data-action="editor-tab" data-tab="${key}" class="${S.tab===key?'active':''}">${label}</button>`).join('')}</div><div class="editor-form">${form}</div><div class="editor-footer"><small id="draft-state">${d.dirty?'● 저장 전 변경 있음':d.current?'✓ 저장된 티켓':'새 티켓을 작성하세요'}</small><div class="actions">${btn('validate','검증')}${btn('save','저장')}${btn('run',!state.enabled?'계산 중':d.dirty||!d.current?'저장 후 실행':state.state==='queued'?'큐 등록됨':'▶ 실행','primary',!state.enabled?'disabled':'')}</div></div></section>`;
}
function exportRows(){return S.draft.values.exports.map((e,i)=>`<div class="export-row"><div class="export-top"><h3>요청 데이터 ${i+1}</h3>${btn('remove-export','삭제','small danger',`data-index="${i}"`)}</div><div class="form-grid"><div class="field"><label for="ex-name-${i}">이름</label><input id="ex-name-${i}" data-export="${i}" data-key="name" value="${attr(e.name)}" placeholder="영문·숫자·_·-"></div><div class="field"><label for="ex-kind-${i}">형식</label><select id="ex-kind-${i}" data-export="${i}" data-key="kind"><option value="document" ${e.kind!=='photo'?'selected':''}>파일</option><option value="photo" ${e.kind==='photo'?'selected':''}>이미지</option></select></div><div class="field full"><label for="ex-path-${i}">상대 경로 / 패턴</label><div class="input-action"><input id="ex-path-${i}" data-export="${i}" data-key="pattern" value="${attr(e.pattern)}" placeholder="validation/live/steady_coupled_naoh.png">${btn('browse','파일 선택','',`data-field-target="export:${i}"`)}</div></div><div class="field"><label for="ex-max-${i}">최대 파일 수 (1–10)</label><input id="ex-max-${i}" type="number" min="1" max="10" data-export="${i}" data-key="max_files" value="${attr(e.max_files||1)}"></div></div></div>`).join('');}
function ticketPage(){return heading('TICKET WORKSPACE','티켓 관리','폼으로 설정하고, 같은 티켓을 Telegram과 GUI에서도 사용하세요.',btn('new-single','＋ 개별 티켓')+btn('new-macro','＋ 매크로 만들기','primary'))+`<div class="ticket-layout"><aside class="ticket-list"><div class="list-tools"><input id="ticket-search" type="search" placeholder="티켓 검색…" value="${attr(S.search)}" aria-label="티켓 검색"><div class="list-summary"><label><input type="checkbox" id="select-all">전체 선택</label>${btn('delete-selected','선택 삭제','small danger')}</div></div><div class="ticket-rows" id="ticket-rows">${ticketList()}</div></aside><div id="editor-container">${editor()}</div></div>`;}
function dataPage(){return heading('RESULTS & ARTIFACTS','결과 · 요청 데이터','케이스의 Residual 이미지와 미리 정의한 데이터를 확인하세요.',btn('reload-data','↻ 결과 새로고침'))+`<div class="data-layout"><aside class="panel case-select"><small>등록된 케이스 ${S.cases.length}개</small>${S.cases.length?S.cases.map(c=>`<button data-action="select-data" data-id="${attr(c.id)}" class="${S.dataId===c.id?'active':''}">${esc(c.name)}<small>${esc(c.case_dir)}</small></button>`).join(''):empty('등록된 케이스가 없습니다.')}</aside><div id="data-result">${empty('케이스를 선택하면 결과를 불러옵니다.','▧')}</div></div>`;}
function render(){const page=view();$('#breadcrumb').textContent=names[page];document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));$('#content').innerHTML=({overview,queue:queuePage,tickets:ticketPage,data:dataPage}[page])();if(page==='data'&&S.dataId)loadData(S.dataId);if(page==='tickets'&&S.draft)controlHint();}
function renderEditor(){if($('#editor-container'))$('#editor-container').innerHTML=editor();controlHint();}
function dirty(){if(!S.draft)return;S.draft.dirty=true;S.draft.request_id=null;if($('#draft-state'))$('#draft-state').textContent='● 저장 전 변경 있음';const run=$('[data-action="run"]');if(run&&!run.disabled)run.textContent='저장 후 실행';}
async function controlHint(){const dir=S.draft?.values.case_dir;if(!dir||!$('#control-hint'))return;try{const c=await api('/api/control?'+new URLSearchParams({path:dir}));if($('#control-hint')&&S.draft?.values.case_dir===dir)$('#control-hint').innerHTML=`<p class="foot-note">controlDict 기본 종료 값: <strong>${esc(c?.end??'읽을 수 없음')}</strong>${c?.stop_at?' · stopAt '+esc(c.stop_at):''}</p>`;}catch{}}
async function refresh(){if(S.refreshing)return;S.refreshing=true;$('#sync-label').textContent='상태 확인 중…';try{S.overview=await api('/api/overview');$('#ticket-count').textContent=S.overview.tickets.length;$('#queue-count').textContent=S.overview.queue.length;const error=S.overview.error;$('#connection-error').textContent=error?'최신 상태를 읽지 못했습니다. 마지막으로 확인한 상태를 표시합니다.\n'+error:'';$('#connection-error').hidden=!error;$('#sync-label').textContent=error?'상태 확인 실패':`갱신 ${new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`;if(['overview','queue'].includes(view()))render();else if(view()==='tickets'){if($('#ticket-rows'))$('#ticket-rows').innerHTML=ticketList();const state=S.overview.tickets.find(t=>t.filename===S.draft?.current);const run=$('[data-action="run"]');if(state&&run){run.disabled=!state.enabled;run.textContent=!state.enabled?'계산 중':S.draft?.dirty?'저장 후 실행':state.state==='queued'?'큐 등록됨':'▶ 실행';}}}catch(e){$('#connection-error').textContent='웹 서버에 연결할 수 없습니다. '+e.message;$('#connection-error').hidden=false;$('#sync-label').textContent='연결 끊김';}finally{S.refreshing=false;}}
async function openTicket(name){S.draft=await api('/api/ticket?'+new URLSearchParams({name}));S.tab='basic';S.postprocessed=S.draft.postprocessed||[];location.hash='tickets';render();}
async function newTicket(kind){S.draft=await api('/api/new',{kind});S.tab='basic';S.postprocessed=S.draft.postprocessed||[];location.hash='tickets';render();}
async function validateExports(){const v=S.draft.values;for(let i=0;i<v.exports.length;i++)v.exports[i]=await api('/api/exports/validate',{case_dir:v.case_dir,item:v.exports[i],others:v.exports,index:i});}
async function saveNow(){await validateExports();const d=S.draft;d.request_id ||= crypto.randomUUID();const saved=await api('/api/save',d);S.draft=saved;S.cases=await api('/api/cases');await refresh();renderEditor();if($('#ticket-rows'))$('#ticket-rows').innerHTML=ticketList();return saved;}
function save(){if(!S.draft)return;const v=S.draft.values;if(v.task_type==='macro'&&!S.draft.current){modal('매크로 저장 및 큐 등록',`<p>${v.cases.length}개 케이스의 하위 티켓을 생성하고 순서대로 큐에 등록합니다.\n\n전처리: ${esc(v.preprocess||'없음')}\n실행: ${esc(v.macro_command)}\nCPU: ${esc(v.macro_cores)}개 · ${v.macro_cpu_policy==='auto'?'자동 배정':esc(v.macro_cpu_set)}\n후처리: ${esc(v.postprocess||'없음')}</p><div class="notice warning">큐가 활성화되어 있으면 가용 CPU 확보 후 계산을 시작합니다.</div>`,'저장 및 큐 등록',async()=>{await saveNow();toast('매크로를 저장하고 큐에 등록했습니다.');});}else return saveNow().then(()=>toast('티켓을 저장했습니다.'));}
function requestRun(){if(!S.draft)return;const d=S.draft,v=d.values;modal(d.dirty||!d.current?'저장 후 실행':'계산 실행 요청',`<p><strong>${esc(v.name||v.case_dir)}</strong>\n${esc(v.case_dir)}\n\n${v.task_type==='macro'?`${v.cases.length}개 케이스 · CPU ${esc(v.macro_cores)}개\n`:v.execution_source==='ticket'?`CPU ${esc(v.macro_cores)}개\n`:''}전처리: ${esc(v.preprocess||'없음')}\n후처리: ${esc(v.postprocess||'없음')}</p><div class="notice warning">실행 전 전처리를 수행합니다. Allclean이 포함되어 있으면 기존 계산 결과를 정리할 수 있습니다.</div>`,'실행 요청',async()=>{if(d.dirty||!d.current)await saveNow();const result=await api('/api/run',{name:S.draft.current,revision:S.draft.revision,request_id:crypto.randomUUID()});toast(result.already_queued?'이미 큐에 등록된 작업입니다.':'실행 요청을 큐에 등록했습니다.');await refresh();renderEditor();});}
async function loadData(id){S.dataId=id;const result=$('#data-result');if(!result)return;result.innerHTML=empty('케이스 결과를 읽는 중…');try{const [detail,groups]=await Promise.all([api('/api/detail?case='+encodeURIComponent(id)),api('/api/artifacts?case='+encodeURIComponent(id))]);if(S.dataId!==id||!$('#data-result'))return;const c=S.cases.find(c=>c.id===id);$('#data-result').innerHTML=`<section class="panel"><div class="panel-head"><div><h2>${esc(detail.name)}</h2><small class="mono">${esc(detail.case_dir)}</small></div>${c?.ticket?btn('open-ticket','티켓 편집','small',`data-name="${attr(c.ticket)}"`):''}</div><div class="panel-body"><div class="detail-grid"><div><small>현재 / 목표</small><strong>${esc(detail.telemetry.time??'—')} / ${esc(detail.estimate.target??detail.control?.end??'—')}</strong></div><div><small>최근 상태</small>${detail.latest?badge(detail.latest.status):'—'}</div><div><small>예상 남은 시간</small><strong>${duration(detail.estimate.remaining_seconds)}</strong></div></div><p class="foot-note">로그: ${esc(detail.log)}</p>${detail.latest?.reason?`<p class="details-reason">${esc(detail.latest.reason)}</p>`:''}${detail.telemetry.errors?.length?`<p class="error-detail">${esc(detail.telemetry.errors.join('\n'))}</p>`:''}</div></section>${groups.length?groups.map(g=>`<section class="panel"><div class="panel-head"><div><h2>${g.name==='residual'?'Residual':esc(g.name)}</h2><small class="mono">${esc(g.pattern)}</small></div><small>${g.files.length}개 파일</small></div><div class="panel-body">${g.error?`<div class="notice danger">${esc(g.error)}</div>`:''}${!g.files.length?empty('이 경로에 일치하는 파일이 아직 없습니다.'):`<div class="artifact-grid">${g.files.map(f=>`<article class="artifact">${f.preview&&!f.too_large?`<a href="${attr(f.url)}" target="_blank" rel="noopener"><img src="${attr(f.url)}" alt="${attr(f.name)}" loading="lazy"></a>`:''}<div class="artifact-info"><p class="mono">${esc(f.path)}</p><p><small>${bytes(f.size)} · ${stamp(f.modified)}</small></p>${f.too_large?'<small>49 MiB를 초과합니다.</small>':`<a href="${attr(f.url)}&amp;download=1" download>↓ 다운로드</a>`}</div></article>`).join('')}</div>`}</div></section>`).join(''):empty('티켓에 Residual 또는 요청 데이터 경로를 추가하세요.')}`;}catch(e){if($('#data-result'))$('#data-result').innerHTML=`<div class="notice danger">${esc(e.message)}</div>`;}}
async function browse(target,path){const v=S.draft.values,dir=(target!=='case_dir'&&v.task_type==='macro'&&v.cases.length?v.cases[0].case_dir:v.case_dir)||S.defaultDirectory;S.browser={target,root:target==='case_dir'?'':dir,path:path||dir};await showBrowser();}
async function showBrowser(){const b=S.browser;const result=await api('/api/browse?'+new URLSearchParams({path:b.path,root:b.root,kind:b.target==='case_dir'?'directory':'file'}));b.path=result.path;b.root=result.root;modal(b.target==='case_dir'?'케이스 폴더 선택':'케이스 내 파일 선택',`<div class="browser-path"><input id="browser-path" aria-label="탐색 경로" value="${attr(result.path)}">${btn('browse-go','이동')}</div><div class="actions">${result.parent?btn('browse-parent','↑ 상위 폴더','small',`data-path="${attr(result.parent)}"`):''}</div><div>${result.entries.map(e=>`<button class="file-row" data-action="${e.directory?'browse-folder':'pick-file'}" data-path="${attr(e.path)}"><span>${e.directory?'▰':'▤'}</span>${esc(e.name)}${e.directory?' /':''}</button>`).join('')||empty('비어 있는 폴더입니다.')}</div>${result.truncated?'<div class="notice warning">최대 1,000개 항목을 표시합니다. 경로를 직접 입력해 이동할 수 있습니다.</div>':''}`,b.target==='case_dir'?'이 폴더 선택':null,b.target==='case_dir'?()=>pickPath(b.path):null);}
function pickPath(path){const b=S.browser,v=S.draft.values;if(b.target==='case_dir')v.case_dir=path;else{const relative=path.slice(b.root.replace(/\/$/,'').length+1);if(b.target==='logs')v.logs=[...new Set([...v.logs.split('\n').filter(Boolean),relative])].join('\n');else if(b.target.startsWith('export:'))v.exports[Number(b.target.split(':')[1])].pattern=relative;else v[b.target]=relative;}dirty();$('#modal').close();renderEditor();}
async function action(button){const a=button.dataset.action,d=S.draft,v=d?.values;
  switch(a){
    case 'client-downloads':modal('PC에서 더블클릭으로 열기',`<p>ZIP을 압축 해제한 뒤 실행 파일을 여세요. 기존 SSH config의 Host 목록에서 번호를 선택하면 연결 후 브라우저를 엽니다. 기존 SSH 포트와 키 설정을 그대로 사용합니다.</p><div class="actions"><a href="/downloads/CFD-Control-Room-Windows.zip" download>↓ Windows ZIP</a><a href="/downloads/CFD-Control-Room-macOS.zip" download>↓ macOS ZIP</a></div><p class="foot-note">Windows: Start CFD.cmd · macOS: CFD Control Room.app<br>기본 서버 웹 포트: 8766. 연결 창은 사용 중 최소화해 두세요. 비밀번호는 저장하지 않습니다.</p>`,null);break;
    case 'refresh': await refresh();break;
    case 'new-single':return confirmDiscard(()=>newTicket('single'));
    case 'new-macro':return confirmDiscard(()=>newTicket('macro'));
    case 'open-ticket':return confirmDiscard(()=>openTicket(button.dataset.name));
    case 'duplicate-ticket':return confirmDiscard(async()=>{S.draft=await api('/api/duplicate',{name:d.current});S.tab='basic';render();toast('복제 초안을 만들었습니다. 케이스 경로를 지정해 저장하세요.');});
    case 'editor-tab':S.tab=button.dataset.tab;renderEditor();break;
    case 'validate':await validateExports();await api('/api/validate',S.draft);toast('티켓 검증을 통과했습니다.');break;
    case 'save':return save();
    case 'run':return requestRun();
    case 'delete-selected':{if(!S.selected.size)throw new Error('삭제할 티켓을 선택하세요.');const plan=await api('/api/delete/preview',{names:[...S.selected]});modal('티켓 일괄 삭제',`<p>${plan.names.length}개 티켓을 삭제합니다. 매크로의 하위 티켓도 포함됩니다. 케이스 디렉토리와 계산 결과는 유지됩니다.</p><p class="mono">${plan.names.map(esc).join('\n')}</p>`,'선택 티켓 삭제',async()=>{await api('/api/delete',plan);if(plan.names.includes(S.draft?.current))S.draft=null;S.selected.clear();await refresh();render();toast('선택한 티켓을 삭제했습니다.');},true);break;}
    case 'add-export':v.exports.push({name:'',pattern:'',kind:'document',max_files:1,on:[],on_complete:false});dirty();renderEditor();break;
    case 'remove-export':v.exports.splice(Number(button.dataset.index),1);dirty();renderEditor();break;
    case 'apply-preset':{const rules=S.patterns[$('#preset').value];v.failure_patterns=rules.failure_patterns.join('\n');v.openfoam_defaults=rules.openfoam_defaults;dirty();renderEditor();break;}
    case 'save-preset':modal('실패 패턴 템플릿 저장','<div class="field"><label for="preset-name">템플릿 이름</label><input id="preset-name" maxlength="80" placeholder="예: coupled steady"></div>','템플릿 저장',async()=>{S.patterns=await api('/api/patterns',{name:$('#preset-name').value,rules:{failure_patterns:v.failure_patterns.split('\n').filter(x=>x.trim()),openfoam_defaults:v.openfoam_defaults}});renderEditor();toast('GUI와 Telegram에서도 사용할 수 있는 템플릿을 저장했습니다.');});break;
    case 'discover':{if(!v.case_dir)throw new Error('먼저 Case directory를 지정하세요.');const search=async()=>{const r=await api('/api/discover',{case_dir:v.case_dir,end_time:v.end_time});v.cases=r.cases;S.postprocessed=r.postprocessed;dirty();renderEditor();toast(`${r.cases.length}개 케이스 검색 · 실행 중 ${r.skipped.length}개 제외`);};if(v.cases.length)modal('하위 케이스 다시 검색','<p>선택 목록을 현재 검색 결과로 교체합니다. 저장 전에는 기존 티켓에 반영되지 않습니다.</p>','검색',search);else await search();break;}
    case 'remove-case':v.cases.splice(Number(button.dataset.index),1);dirty();renderEditor();break;
    case 'case-up':case 'case-down':{const i=Number(button.dataset.index),j=i+(a==='case-up'?-1:1);[v.cases[i],v.cases[j]]=[v.cases[j],v.cases[i]];dirty();renderEditor();break;}
    case 'browse':await browse(button.dataset.fieldTarget);break;
    case 'browse-go':S.browser.path=$('#browser-path').value;await showBrowser();break;
    case 'browse-folder':case 'browse-parent':S.browser.path=button.dataset.path;await showBrowser();break;
    case 'pick-file':pickPath(button.dataset.path);break;
    case 'close-modal':$('#modal').close();break;
    case 'confirm-modal':{const fn=modalAction;if(fn){await fn();$('#modal').close();}break;}
    case 'pause-queue':case 'resume-queue':await api('/api/queue',{action:a==='pause-queue'?'pause':'resume'});await refresh();toast(a==='pause-queue'?'새 계산의 자동 시작을 일시 정지했습니다.':'큐 자동 시작을 재개했습니다.');break;
    case 'cancel-job':modal('대기 작업 취소','<p>이 작업을 대기 큐에서 취소합니다. 이미 시작된 작업은 취소되지 않습니다.</p>','대기 취소',async()=>{await api('/api/queue',{action:'cancel',id:button.dataset.id});await refresh();},true);break;
    case 'job-detail':{const j=S.overview.history.find(j=>j.id===button.dataset.id);modal('실행 상세',`<p><strong>${esc(j.name)}</strong>\n${esc(j.case_dir)}\n\n${esc(statusNames[j.status])} · ${stamp(j.finished)}\nCPU: ${esc(j.actual_cpu_list||'—')}</p><p class="details-reason">${esc(j.reason||'기록된 추가 사유가 없습니다.')}</p>`,null);break;}
    case 'case-data':S.dataId=button.dataset.id;location.hash='data';if(view()==='data')render();break;
    case 'select-data':S.dataId=button.dataset.id;render();break;
    case 'reload-data':S.cases=await api('/api/cases');render();break;
  }
}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button||button.disabled)return;event.preventDefault();if(S.busy&&button.dataset.action!=='close-modal')return;S.busy=true;$('#content').inert=true;button.disabled=true;try{await action(button);}catch(e){toast(e.message,true);}finally{S.busy=false;$('#content').inert=false;if(button.isConnected)button.disabled=false;const run=$('[data-action="run"]');const state=S.overview?.tickets.find(t=>t.filename===S.draft?.current);if(run&&state&&!state.enabled)run.disabled=true;}});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='ticket-search'){S.search=el.value;$('#ticket-rows').innerHTML=ticketList();return;}if(!S.draft)return;if(el.dataset.field){S.draft.values[el.dataset.field]=el.type==='checkbox'?el.checked:el.value;dirty();}if(el.hasAttribute('data-filename')){S.draft.filename=el.value;dirty();}if(el.dataset.export!==undefined){S.draft.values.exports[Number(el.dataset.export)][el.dataset.key]=el.dataset.key==='max_files'?Number(el.value):el.value;dirty();}if(el.dataset.event){S.draft.values.events=[...document.querySelectorAll('[data-event]:checked')].map(x=>x.dataset.event);dirty();}});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.select){el.checked?S.selected.add(el.dataset.select):S.selected.delete(el.dataset.select);}if(el.id==='select-all'){for(const t of (S.overview?.tickets||[]).filter(t=>(t.name+' '+t.filename).toLowerCase().includes(S.search.toLowerCase())))el.checked?S.selected.add(t.filename):S.selected.delete(t.filename);$('#ticket-rows').innerHTML=ticketList();}if(['task_type','role','macro_cpu_policy','execution_source'].includes(el.dataset.field))renderEditor();if(el.dataset.field==='case_dir')controlHint();});
window.addEventListener('hashchange',render);
window.addEventListener('beforeunload',event=>{if(S.draft?.dirty){event.preventDefault();event.returnValue='';}});
async function start(){try{const boot=await api('/api/bootstrap');S.csrf=boot.csrf;S.patterns=boot.patterns;S.defaultDirectory=boot.default_directory;S.cases=await api('/api/cases');render();await refresh();setInterval(()=>{if(!document.hidden&&!S.busy)refresh();},10000);}catch(e){$('#content').innerHTML=`<div class="notice danger">${esc(e.message)}<p>페이지를 새로고침해 다시 연결하세요.</p></div>`;}}
start();
